import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await (await b.newContext({viewport:{width:1200,height:900}})).newPage()
p.on('console', m => console.log('CONSOLE:', m.type(), m.text().slice(0,300)))
await p.goto('http://localhost:3000/login', { waitUntil:'networkidle' })
await p.getByLabel('Phone number').fill('+46709900001')
await p.getByRole('button', { name:'Send code' }).click()
await p.waitForTimeout(6000)
console.log('URL:', p.url())
console.log('BODY:', (await p.locator('body').innerText()).slice(0,900))
await p.screenshot({ path:'/private/tmp/claude-501/-Users-fridabredberg-dev-sports-event-manager/df24f1b6-e281-4fcc-9379-e7c6342d612f/scratchpad/login-state.png' })
await b.close()
